# matsushibadenki/snn/configs/models/medium.yaml
# 中規模モデルのアーキテクチャ設定

model:
  path: "breakthrough_snn_model_medium.pth"
  d_model: 256
  d_state: 128
  num_layers: 8
  time_steps: 20
  n_head: 4
  # ニューロン設定
  neuron:
    type: "lif" # "lif" または "dendritic"
    # typeが "dendritic" の場合のみ使用されるパラメータ
    num_branches: 4
    branch_features: 64 # 例: d_model / num_branches
